/*
 * Copyright 2014 Ivashin Alexey <ivashin.alexei@gmail.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ru.fedul0x.ic.gui;

import java.awt.CardLayout;
import ru.fedul0x.ic.dataaccess.DataSourceHibernate;
import ru.fedul0x.ic.dataaccess.dataobject.ContaminationByFederalClassification;
import ru.fedul0x.ic.dataaccess.dataobject.ContaminationComposition;
import ru.fedul0x.ic.dataaccess.dataobject.DataSheet;

/**
 *
 * @author Ivashin Alexey <ivashin.alexei@gmail.com>
 */
public class DataSheetInputPanel extends javax.swing.JPanel {

    private DataSheet dataSheet;
    private ContaminationComposition contaminationComposition;

    /**
     * Creates new form DataSheetInputPanel
     */
    //editable inside
    public DataSheetInputPanel() {
        initComponents();
        dataSheet = new DataSheet();
    }

    public DataSheetInputPanel(DataSheet dataSheet) {
        initComponents();
        this.dataSheet = dataSheet;
    }
    
    //editable outside
    public synchronized ContaminationComposition getContaminationComposition() {
        return contaminationComposition;
    }

    public synchronized void setContaminationComposition(ContaminationComposition contaminationComposition) {
        this.contaminationComposition = contaminationComposition;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jtxtGangeriousClass = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtFederalClassification = new javax.swing.JTextField();
        jtxtFederalName = new javax.swing.JTextField();
        jbtnSaveDataSheet = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlblContaminationComposition = new javax.swing.JLabel();
        jtxtContaminationComposition = new javax.swing.JTextField();
        jbtnContaminationComposition = new javax.swing.JButton();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        setLayout(layout);

        jLabel1.setText("Класс опасности");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(jLabel1, gridBagConstraints);

        jtxtGangeriousClass.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(jtxtGangeriousClass, gridBagConstraints);

        jLabel2.setText("Классификация по ФККО");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(jLabel2, gridBagConstraints);

        jLabel3.setText("Наименование по ФККО");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(jtxtFederalClassification, gridBagConstraints);

        jtxtFederalName.setEditable(false);
        jtxtFederalName.setBackground(new java.awt.Color(230, 230, 230));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(jtxtFederalName, gridBagConstraints);

        jbtnSaveDataSheet.setAlignmentX(0.5F);
        jbtnSaveDataSheet.setLabel("Сохранить");
        jbtnSaveDataSheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveDataSheetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 12;
        add(jbtnSaveDataSheet, gridBagConstraints);

        jbtnCancel.setAlignmentX(0.5F);
        jbtnCancel.setLabel("Отмена");
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 12;
        add(jbtnCancel, gridBagConstraints);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.weighty = 1.0;
        add(jPanel2, gridBagConstraints);

        jlblContaminationComposition.setText("Состав отхода");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(jlblContaminationComposition, gridBagConstraints);

        jtxtContaminationComposition.setEditable(false);
        jtxtContaminationComposition.setBackground(new java.awt.Color(230, 230, 230));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(jtxtContaminationComposition, gridBagConstraints);

        jbtnContaminationComposition.setText("...");
        jbtnContaminationComposition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnContaminationCompositionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 8;
        add(jbtnContaminationComposition, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSaveDataSheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveDataSheetActionPerformed
        //TODO rewrite this
        dataSheet.setContamination(new ContaminationByFederalClassification());
        dataSheet.setDangerousCode(Byte.MIN_VALUE);
//        dataSheet.setСontaminationComposition(new ContaminationComposition());
        
        DataSourceHibernate<DataSheet> dsh = new DataSourceHibernate<>(DataSheet.class);
        dsh.makePersistent(dataSheet);
        if (getParent() instanceof CompanyInputPanel) {
            ((CompanyInputPanel) getParent()).setDataSheet(dataSheet);
        }
        ((CardLayout)getParent().getLayout()).previous(getParent());
        getParent().remove(this);
    }//GEN-LAST:event_jbtnSaveDataSheetActionPerformed

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        ((CardLayout)getParent().getLayout()).previous(getParent());
        getParent().remove(this);
    }//GEN-LAST:event_jbtnCancelActionPerformed

    private void jbtnContaminationCompositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnContaminationCompositionActionPerformed
        //next dialog 
        ContaminationCompositionInputPanel ccip = new ContaminationCompositionInputPanel();
        getParent().add(ccip, "ccip");
        ((CardLayout) getParent().getLayout()).next(getParent());
    }//GEN-LAST:event_jbtnContaminationCompositionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnContaminationComposition;
    private javax.swing.JButton jbtnSaveDataSheet;
    private javax.swing.JLabel jlblContaminationComposition;
    private javax.swing.JTextField jtxtContaminationComposition;
    private javax.swing.JTextField jtxtFederalClassification;
    private javax.swing.JTextField jtxtFederalName;
    private javax.swing.JTextField jtxtGangeriousClass;
    // End of variables declaration//GEN-END:variables
}
