/*
 * Copyright 2014 Ivashin Alexey <ivashin.alexei@gmail.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ru.fedul0x.ic.gui;

import java.awt.CardLayout;
import ru.fedul0x.ic.dataaccess.dataobject.ContaminationByFederalClassification;
import ru.fedul0x.ic.dataaccess.dataobject.DataOperator;
import ru.fedul0x.ic.view.component.model.HibernateRowTableModel;

/**
 *
 * @author Ivashin Alexey <ivashin.alexei@gmail.com>
 */
public class MainFrame extends javax.swing.JFrame {

    private DataOperator currentOperator = null;

    public synchronized DataOperator getCurrentOperator() {
        return currentOperator;
    }

    public synchronized void setCurrentOperator(DataOperator currentOperator) {
        this.currentOperator = currentOperator;
        if (null != currentOperator) {
            jmenuStart.setText(currentOperator.getLogin());
            jmenuDatabaseSettings.setEnabled(false);
            jitemLogin.setEnabled(false);
            jitemLogout.setEnabled(true);
        } else {
            jmenuStart.setText("Начало");
            jmenuDatabaseSettings.setEnabled(true);
            jitemLogin.setEnabled(true);
            jitemLogout.setEnabled(false);
        }
    }

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setCurrentOperator(null);
          ContaminationCompositionInputPanel2 ccip = new ContaminationCompositionInputPanel2();
       this.add(ccip, "ccip");
        ((CardLayout) getContentPane().getLayout()).show(this.getContentPane(), "ccip");
        this.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenuStart = new javax.swing.JMenu();
        jmenuDatabaseSettings = new javax.swing.JMenuItem();
        jitemLogin = new javax.swing.JMenuItem();
        jitemLogout = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jitemExit = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmenuUserActions = new javax.swing.JMenu();
        jitemCompanyInput = new javax.swing.JMenuItem();
        jmenuHandbook = new javax.swing.JMenu();
        jitemFKKO = new javax.swing.JMenuItem();
        jmenuAbout = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(jPanel1, "card2");

        jmenuStart.setText("Начало");

        jmenuDatabaseSettings.setText("Настройки БД");
        jmenuDatabaseSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuDatabaseSettingsActionPerformed(evt);
            }
        });
        jmenuStart.add(jmenuDatabaseSettings);

        jitemLogin.setText("Вход");
        jitemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jitemLoginActionPerformed(evt);
            }
        });
        jmenuStart.add(jitemLogin);

        jitemLogout.setText("Выход");
        jitemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jitemLogoutActionPerformed(evt);
            }
        });
        jmenuStart.add(jitemLogout);
        jmenuStart.add(jSeparator2);

        jitemExit.setText("Выход из программы");
        jitemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jitemExitActionPerformed(evt);
            }
        });
        jmenuStart.add(jitemExit);
        jmenuStart.add(jSeparator1);

        jMenuBar1.add(jmenuStart);

        jmenuUserActions.setText("Действия");

        jitemCompanyInput.setText("Добавить организацию");
        jitemCompanyInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jitemCompanyInputActionPerformed(evt);
            }
        });
        jmenuUserActions.add(jitemCompanyInput);

        jMenuBar1.add(jmenuUserActions);

        jmenuHandbook.setText("Справочники");

        jitemFKKO.setText("ФККО");
        jitemFKKO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jitemFKKOActionPerformed(evt);
            }
        });
        jmenuHandbook.add(jitemFKKO);

        jMenuBar1.add(jmenuHandbook);

        jmenuAbout.setText("О программе");

        jMenuItem2.setText("jMenuItem2");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmenuAbout.add(jMenuItem2);

        jMenuBar1.add(jmenuAbout);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jitemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jitemLoginActionPerformed
        LoginFrame.main(this);

    }//GEN-LAST:event_jitemLoginActionPerformed

    private void jmenuDatabaseSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuDatabaseSettingsActionPerformed
        DatabaseSettingsFrame.main();
    }//GEN-LAST:event_jmenuDatabaseSettingsActionPerformed

    private void jitemFKKOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jitemFKKOActionPerformed
//        String fields[] = {"code", "description", "dangerousCode"};
        String fields[] = {"Код", "Описание", "Класс опасности"};
        HibernateRowTableModel<ContaminationByFederalClassification> hrtm = new HibernateRowTableModel(ContaminationByFederalClassification.class, fields);
        TablePanel tp = new TablePanel(hrtm, false);
        this.add(tp, "tp");
        ((CardLayout) getContentPane().getLayout()).next(this.getContentPane());
    }//GEN-LAST:event_jitemFKKOActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
//        (getContentPane().getLayout()).show(jButton1, "sfd");
//        ((CardLayout)getContentPane().getLayout()).next(this);
//        ((CardLayout)jPanel1.getLayout()).next(this);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jitemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jitemLogoutActionPerformed
        setCurrentOperator(null);
    }//GEN-LAST:event_jitemLogoutActionPerformed

    private void jitemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jitemExitActionPerformed
        dispose();
    }//GEN-LAST:event_jitemExitActionPerformed

    private void jitemCompanyInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jitemCompanyInputActionPerformed
        CompanyInputPanel cip = new CompanyInputPanel();
        this.add(cip, "cip");
        ((CardLayout) getContentPane().getLayout()).show(this.getContentPane(), "cip");

        this.revalidate();
        
        ContaminationCompositionInputPanel2 ccip = new ContaminationCompositionInputPanel2();
       this.add(ccip, "ccip");
        ((CardLayout) getContentPane().getLayout()).show(this.getContentPane(), "ccip");
        this.revalidate();
    }//GEN-LAST:event_jitemCompanyInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem jitemCompanyInput;
    private javax.swing.JMenuItem jitemExit;
    private javax.swing.JMenuItem jitemFKKO;
    private javax.swing.JMenuItem jitemLogin;
    private javax.swing.JMenuItem jitemLogout;
    private javax.swing.JMenu jmenuAbout;
    private javax.swing.JMenuItem jmenuDatabaseSettings;
    private javax.swing.JMenu jmenuHandbook;
    private javax.swing.JMenu jmenuStart;
    private javax.swing.JMenu jmenuUserActions;
    // End of variables declaration//GEN-END:variables
}
